spring.application.name=WiproCircuitBreakerDemo
server.port=8080

management.endpoints.web.exposure.include=*
resilience4j.circuitbreaker.instances.deliveryCB.register-health-indicator=true
resilience4j.circuitbreaker.instances.deliveryCB.sliding-window-size=5
resilience4j.circuitbreaker.instances.deliveryCB.minimum-number-of-calls=3
resilience4j.circuitbreaker.instances.deliveryCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.deliveryCB.wait-duration-in-open-state=5s
resilience4j.circuitbreaker.instances.deliveryCB.permitted-number-of-calls-in-half-open-state=2
resilience4j.circuitbreaker.instances.deliveryCB.automatic-transition-from-open-to-half-open-enabled=true
